field.field.*.*.*.third_party.comments_order:
  type: mapping
  label: 'Extra settings for Comments Order'
  mapping:
    order:
      type: label
      label: 'Order'
    children_natural_order:
      type: integer
      label: 'Children Natural Order'
