access_records.type.*:
  type: config_entity
  label: 'Access record type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    status:
      type: boolean
      label: 'Whether access records should be enabled by default.'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    label_pattern:
      type: string
      label: 'A pattern to use for creating the label of the access record'
    subject_type:
      type: string
      label: 'The assigned subject entity type (mostly "user").'
    target_type:
      type: string
      label: 'The assigned target entity type access records of this type belong to.'
    operations:
      type: sequence
      label: 'Allowed operations'
      sequence:
        type: string
        label: 'Allowed operation'
