views.relationship.access_record_data:
  type: views_relationship
  label: 'Access records'
  mapping:
    types:
      type: sequence
      label: 'Access record types'
      sequence:
        type: string
        label: 'Access record type'
    match:
      type: string
      label: 'Match criteria'

views.relationship.access_record_subject:
  type: views_relationship
  label: 'Access record subjects'

views.relationship.access_record_target:
  type: views_relationship
  label: 'Access record targets'

views.field.access_record_subject_id:
  type: views_field
  label: 'Access record subject ID'
  mapping:
    format:
      type: string
      label: 'Format'
    link:
      type: boolean
      label: 'Link to the subject page'

views.field.access_record_target_id:
  type: views_field
  label: 'Access record target ID'
  mapping:
    format:
      type: string
      label: 'Format'
    link:
      type: boolean
      label: 'Link to the target page'
